// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'movie': string;
  'movie__background': string;
  'movie__title': string;
}
export const cssExports: CssExports;
export default cssExports;
