// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'embed-responsive': string;
  'tv-video': string;
}
export const cssExports: CssExports;
export default cssExports;
