// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'item__background': string;
  'item__content': string;
  'item__image': string;
  'item__image--loaded': string;
  'item__image-container': string;
  'item__thumbnail': string;
  'item__title': string;
}
export const cssExports: CssExports;
export default cssExports;
