// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fadeEffect': string;
  'item-skeleton': string;
  'item-skeleton__content': string;
  'item-skeleton__image-container': string;
}
export const cssExports: CssExports;
export default cssExports;
